config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'
  
  get 'hello' => 'application#hello'
  
  get 'test'    => 'static_pages#test'

  root 'static_pages#home'
  
  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'settings'   => 'static_pages#settings'
  get 'guest'   => 'static_pages#guest'
  get 'browse'   => 'browse#home'
  get 'r'   => 'browse#refresh'
  get 'u'   => 'browse#back'
  post 'browses'   => 'browse#upload'
  post 'browse'   => 'browse#fcreate'
  
  get 'signup'  => 'users#new'
  
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    redirect_to browse_url
    else
     @user = User.new
    end
  end

  def help
  end
  
  def about
  end
  
  def settings
  end
  
  def guest
    Dir.chdir("/home/ubuntu/container")
    @files = Dir.glob("*")
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def fname(file)
        ext=fext(file)
        name = file.chomp(ext)
        return name
    end
    
    def fext(file)
    ext=File.extname(file)
    return ext
    end
    
    def mlocation
        path = Dir.pwd
        mypath = path.chomp("/home/ubuntu/container") 
        if mypath==""
            return "Home"
        end
    end
end

app/views/static_pages/_negotiationdetail.html.erb
<div class="modal hide fade" id="modal-window">
  <div class="modal-header">
    <a href="#" class="close">×</a>
    <h3>Loading...</h3>
  </div>
  <div class="modal-body center">
      <%= image_tag "loading.gif" %>
  </div>
  <div class="modal-footer">&nbsp;</div>
</div>

app/views/static_pages/guest.html.erb
<% provide(:title, "Guest") %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Home Server</title>
  </head>
<body>
  <div class="page-header">
  <h1>Guest User <small><%= Dir.pwd %></small></h1>
</div>

<div class = "row">
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Library</a></li>
  <li class="active">Data</li>
</ol>

   

<% @files.each do |file| %>
<div class="col-sm-6 col-md-2">
    <div class="thumbnail">
      <%= image_tag("file.png", alt: "icon") %>
      <div class="caption">
        <h4><%= fname(file) %></h4>
        <% if File.directory? file %>
        <p>Folder</p>
        <% else %>
        <p><b><%= fext(file) %> file</b></p>
        <% end %>
<div class="btn-group dropup">
  <%= link_to "Open", "#", class: "btn btn-primary" %>
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Delete", "#" %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Edit", "#" %></li>
    <li><%= link_to "Info", "#" %></li>
  </ul>
</div></div></div></div>
<% end %>
</div>
 
</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Home Server</title>
  </head>
<body>

    <div class="center jumbotron"><div class="row">
    
    <div id="left" style="float:left; width:63%;">
    <h1>Hello! </h1>
    <h2>
    A home server<br> <br>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" data-backdrop="static">
  Guests, Click here
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Enter User's name you know.</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Browse</button>
      </div>
    </div>
  </div>
</div>
     <br>
    </h2><br>
    <%= link_to image_tag("logo.png", alt: "logo"), 'http://goo.gl/FH7KaX' %>
    <br> <br>
    To know <%= link_to "more", help_path %>
    </div>
    
    
    <div id="right" style="float:right; width:37%;"><br>
    <h2>Welcome back?</h2> <br>
    <div align="left">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :remember_me, class: "checkbox inline" do %> 
        <%= f.check_box :remember_me %>
        <span>Remember this login</span>
      <% end %>
      <%= f.submit "Log In", class: "btn btn-primary" %>
    <% end %></div>
    <br><br> 
    <h3> Ask for admin access <%= link_to "here ", signup_path %></h3>
    </div>
    
    </div></div>
</body>
</html>

app/views/static_pages/settings.html.erb
<% provide(:title, "Settings") %>
<h1>Settings</h1>
<div class = "col-sm-6">
<div class="checkbox">
  <label><input type="checkbox" value="">Remember path?</label>
</div></div>

app/views/static_pages/test.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Title</h4>
      </div>
      <div class="modal-body">
        <%= image_tag("hourglass.svg", alt: "loading") %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>