config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'
  
  get 'hello' => 'application#hello'
  
  get 'test'    => 'static_pages#test'

  root 'static_pages#home'
  
  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'settings'   => 'static_pages#settings'
  get 'guest'   => 'static_pages#guest'
  get 'browse'   => 'browse#home'
  get 'r'   => 'browse#refresh'
  get 'u'   => 'browse#back'
  post 'browses'   => 'browse#upload'
  post 'browse'   => 'browse#fcreate'
  
  get 'signup'  => 'users#new'
  
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
end

app/models/browse.rb
class Browse < ActiveRecord::Base
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    mount_uploader :file, FileUploader
    
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
   def home
      if logged_in?
         if params[:f]==nil
            @userpath = params[:to]
            @browse = Browse.new
            
         else
            render 'open'
         end
      else
         redirect_to root_url
      end
   end
   
   def search
   end
   
   def refresh
      redirect_to :back
   end
   
   def back
      redirect_to request.env["HTTP_REFERER"]
   end
   
   def upload
      begin
      @browse = current_user.browses.new(file_params)
      if @browse.save
         flash[:success] = "File Uploaded."
      else
         flash[:danger] = "Some Error Occured"
      end
      rescue CarrierWave::IntegrityError
         flash[:danger] = "Invalid File Type"
      end
    refresh
   end
   
   def fcreate
      begin
      Dir.chdir(cookies[:curpath]) do
         Dir.mkdir(params[:n])
      end
      flash[:info] = "Folder created"
      redirect_to :back
      
      rescue Errno::EEXIST
      flash[:danger] = "Folder name exists"
      refresh
      end
   end

  private

   def file_params
     if params[:browse].present?
      params.require(:browse).permit(:file)
     end
   end
   
   

end

app/helpers/browse_helper.rb
module BrowseHelper
    
    def browse(to, search)
      if search == nil
      if to == nil
        path="/home/ubuntu/workspace/public/container"
        uploadPath = "container"
      else
        path="/home/ubuntu/workspace/public/container/"+to
        uploadPath = "container/"+to
      end
      
      @uploadPath = uploadPath
      user = User.find(current_user.id)
      user.update_attribute(:uploadPath, uploadPath)
      
      if Dir.exists? path
        @sanepath = true
        Dir.chdir(path) do
          @files = Dir.glob("*.*")
          folder = Dir.glob("*")
          @folders = folder - @files
          @path = Dir.pwd
          cookies[:curpath] = @path
        end
      else
          @sanepath = false
          flash[:danger] = "You seem to have a broken link!"
          redirect_to root_url
      end
      
      else
        @searching = true
        @files = []
        @folders = []
      end
    end
    
    def pathSplit(path)
        if path == nil
            ret = ["Home"]
        else
            ret = path.split('/')
            ret.insert(0,"Home")
        end
        return ret
    end
    
    def pathLink(path,goto)
        if path == nil || goto == "Home"
            ret = browse_url
        else
            point = path =~ Regexp.union(goto)
            len = goto.length
            point = point.to_i + len
            y = path.first(point)
            ret = params.merge(to: y)
        end
        return ret
    end
    
    def linkOf(prev,fwd)
        if prev == nil
            return fwd
        else
        return prev+"/"+fwd
        end
    end
    
    def fileSystemPath(pathTo)
        if pathTo == nil
            return "container"
        else
            return "container/"+pathTo
        end
    end
end

app/views/browse/_fnf.html.erb
<% if @folders != nil %>
<div class="col-md-4">
    <div class="panel panel-primary"><div class="panel-heading">
    <h3 class="panel-title">Folders</h3>
  </div>
   <div class="list-group">
<% @folders.each do |folder| %>
<%= link_to folder, params.merge(to:linkOf(pathTo,folder)), class: "list-group-item" %>
  <% end %>
</div></div>
</div><% end %>
<% if @files != nil %>
<div class="col-md-8">
  <div class="panel panel-success"><div class="panel-heading">
    <h3 class="panel-title">Files</h3>
  </div>
  <% @files.each do |file| %>
  <div class="panel-body">

<div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag("/"+@uploadPath+"/"+file, alt: file) %>
      <div class="caption">
        <h4><%= fname(file) %></h4>
        
        <p><b><%= fext(file) %> file</b></p>
        
<div class="btn-group dropup">
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Open
</button>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= fname(file) %></h4>
      </div>
      <div class="modal-body">
        <%= image_tag("/"+@uploadPath+"/"+file, alt: file) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Remove", "#" %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Edit", "#" %></li>
    <li><%= link_to "Info", "#" %></li>
  </ul>
</div></div></div></div>

</div><% end %>
</div>



  </div><% end %>

app/views/browse/_modals.html.erb
<div class="modal" id="uploadFile" tabindex="-1" role="dialog" 
aria-labelledby="exampleModalLabel"><div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="exampleModalLabel">Add Files</h4>
  </div>
  <div class="modal-body">
<%= form_for @browse,  :html => { :multipart => true }  do |f| %>
  

<%= f.file_field :file %>
 </div>
  <div class="modal-footer">
    <%= f.submit 'Upload', :class => 'btn btn-success' %><% end %>
  </div>
</div></div></div>

<div class="modal" id="newFolder" tabindex="-1" role="dialog" 
aria-labelledby="exampleModalLabel"><div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="exampleModalLabel">Create new folder</h4>
  </div>
  <div class="modal-body">
    <%= form_tag() do %>
    <div class="form-group">
    <%= label_tag(:n, "Name :") %>
    <%= text_field_tag :n, "New Folder", class: "form-control" %>
  </div></div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">
      Close</button>
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>Create
    <% end %><% end %>
  </div>
</div></div></div>

app/views/browse/_open.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= params[:f] %></h4>
      </div>
      <div class="modal-body">
        <%= image_tag("/"+fileSystemPath(params[:to])+"/"+params[:f], alt: params[:f]) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

app/views/browse/_tasknav.html.erb
<nav class="navbar navbar-default"  id = "tasknav">

<div class="col-lg-2">
    
<% if @searching %>
<button type="button" class="btn btn-default navbar-btn">Home
<span class="glyphicon glyphicon-home" aria-hidden="true"></span>
</button>
<% else %>
<%= link_to u_url, class: "btn btn-default navbar-btn" do %>
    <i class="glyphicon glyphicon-chevron-left"></i>Back
<% end %>

<% end %>

<%= link_to r_url, class: "btn btn-warning navbar-btn" do %>
    <i class="glyphicon glyphicon-refresh"></i>
<% end %>

</div>

<div class="col-lg-6"><% if !@searching %>

<%= render 'modals' %>
<button type="button" class="btn btn-primary navbar-btn" data-toggle="modal" 
data-target="#newFolder">Add folder
<span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
</button>
<button type="button" class="btn btn-success navbar-btn" data-toggle="modal" 
data-target="#uploadFile">Add file(s)
<span class="glyphicon glyphicon-upload" aria-hidden="true"></span>
</button>

<% end %></div>
<%= form_tag('#', :method => "get") do %>
<div class="col-lg-4"><div class="input-group">





<%= text_field_tag :s, params[:s], placeholder: "Search",
class: "form-control" %>
<span class="input-group-btn">
<%= button_tag(type: 'submit', class: "btn btn-default") do %>
 <i class="icon-ok icon-white"></i> Find</span>
<% end %>




</div></div><% end %>

</nav>

app/views/browse/home.html.erb
<% provide(:title, "Browse") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Home Server</title>
  </head>
<body>
  
<% search = params[:s]
pathTo = params[:to]
f = params[:f]
browse(pathTo, search) %>

<div class = "row">
  <%= render 'tasknav' %>
  
<% if @sanepath %>
<ol class="breadcrumb">
    <% path = pathSplit pathTo
    current = path.last
    path.delete(current)
    path.each do |x| %>
  <li><%= link_to x, pathLink(pathTo,x) %></li>
  <% end %>
  <li class="active"><%= current %></li>
</ol> <% end %>

<% if @searching %>
<div class = "page-header">
  <h1>
    <%= params[:s] %>
    <small>results</small>
  </h1>
</div>
<% end %>

<% if @sanepath || @searching %>

<!-- Folder Listing -->
<div class="col-md-4">
<div class="panel panel-primary">
  <div class="panel-heading"><h3 class="panel-title">Folders</h3></div>
  <div class="list-group">
    <% @folders.each do |folder| %>
      <%= link_to folder, params.merge(to:linkOf(pathTo,folder)),
        class: "list-group-item" %> <% end %>
  </div></div>
</div>

<!-- File Listing -->
<div class="col-md-8">
<div class="panel panel-success">
<div class="panel-heading"><h3 class="panel-title">Files</h3></div>
<div class="panel-body">

<% @files.each do |file| %>
  
<div class="col-sm-6 col-md-3">
  <div class="thumbnail">
      <%= link_to image_tag("/"+@uploadPath+"/"+file, alt: file), 
      params.merge(f:file), remote: true %>
      <div class="caption">
        <h4><%= fname(file) %></h4>
        
        <p><b><%= fext(file) %> file</b></p>
        
<div class="btn-group dropup">
<!-- Button trigger modal -->

<%= link_to "Open", params.merge(f:file), remote: true, class: "btn btn-info" %>

<!-- Modal -->
<div class="modal" id="openModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  
</div>

  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Remove", "#" %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Edit", "#" %></li>
    <li><%= link_to "Info", "#" %></li>
  </ul>
</div></div></div>

</div>

<% end %>
</div></div></div>
<% end %>
</div>
</body>
</html>
 
  

app/views/browse/open.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= current_user.uploadPath %></h4>
      </div>
      <div class="modal-body">
        <%= image_tag("/container/"+params[:f], alt: "file") %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

app/views/browse/open.js.erb
$("#openModal").html("<%= escape_javascript(render 'open') %>")
$("#openModal").modal("show")