config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'
  
  get 'hello' => 'application#hello'
  
  get 'test'    => 'static_pages#test'

  root 'static_pages#home'
  
  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'settings'   => 'static_pages#settings'
  get 'guest'   => 'static_pages#guest'
  get 'browse'   => 'browse#home'
  get 'r'   => 'browse#refresh'
  get 'u'   => 'browse#back'
  post 'browses'   => 'browse#upload'
  post 'browse'   => 'browse#fcreate'
  
  get 'signup'  => 'users#new'
  
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Home Server by 
    <a href="http://www.facebok.com/modi.rajdeep">Rajdeep Modi</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id = "nav1">
  <div class="container">
    <%= link_to "server", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
      
      <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", settings_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% end %>
          </ul>
          
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>
    <%= render 'layouts/header' %>

<div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>